CREATE TABLE IF NOT EXISTS `players` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `identifier` VARCHAR(64) NOT NULL,
    `name` VARCHAR(64) NOT NULL DEFAULT 'Unknown',
    `money` LONGTEXT NOT NULL,
    `job` LONGTEXT NOT NULL,
    `inventory` LONGTEXT NOT NULL,
    `metadata` LONGTEXT NOT NULL,
    `position` LONGTEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `identifier` (`identifier`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
