-- 001: core display registry (idempotent)
CREATE TABLE IF NOT EXISTS `kotzu_displays` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid` CHAR(36) NOT NULL,
    `owner_citizenid` VARCHAR(64) NOT NULL,
    `display_type` VARCHAR(24) NOT NULL,
    `scope_type` VARCHAR(16) NOT NULL,
    `scope_id` VARCHAR(64) NULL,
    `routing_bucket` INT NOT NULL DEFAULT 0,
    `loc_x` DOUBLE NOT NULL,
    `loc_y` DOUBLE NOT NULL,
    `loc_z` DOUBLE NOT NULL,
    `loc_heading` DOUBLE NOT NULL DEFAULT 0,
    `gender` VARCHAR(8) NULL,
    `outfit` LONGTEXT NULL,
    `pose_id` VARCHAR(32) NULL,
    `platform` VARCHAR(32) NULL,
    `item_name` VARCHAR(64) NULL,
    `item_metadata` LONGTEXT NULL,
    `label` VARCHAR(64) NULL,
    `description` VARCHAR(256) NULL,
    `permissions` LONGTEXT NULL,
    `manifest_version` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_uid` (`uid`),
    KEY `idx_scope` (`scope_type`, `scope_id`),
    KEY `idx_owner` (`owner_citizenid`),
    KEY `idx_bucket` (`routing_bucket`),
    KEY `idx_alive` (`deleted_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
